Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("blog.urls")),
    path('admin/', admin.site.urls),
    path("blogUser", include("blogUser.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [
    path("", views.BlogList.as_view(), name="blog_list"),
    path("crear/", views.BlogCreate.as_view(), name="blog_create"),
    path("detalle/<pk>/", views.BlogDetail.as_view(), name ="blog_detail"),
    path("editar/<pk>/", views.BlogUpdate.as_view(), name ="blog_update"),
    path("borrar/<pk>/", views.BlogDelete.as_view(), name ="blog_delete"),
    path("entrar/", views.BlogLogin.as_view(), name="blog_login"),
    path("salir/", views.BlogLogout.as_view(), name="blog_logout"),
    path("no_autorizado/", views.no_autorizado, name="no_autorizado"),
    
]

blogUser/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from blogUser import views

urlpatterns = [
    path("crear/", views.SignUp.as_view(), name ="blogUser_signup"),
    path("profile/<pk>/", views.BlogUserProfile.as_view(), name ="blogUser_profile"),
    path("editar/<pk>/", views.BlogUserUpdate.as_view(), name ="blogUser_edit"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from pyexpat import model
from statistics import mode
from django.db import models
from django.contrib.auth.models import User

class BlogModel(models.Model):
    titulo = models.CharField(max_length=100)
    sub_titulo = models.CharField(max_length=100)
    cuerpo = models.TextField()
    # autor toma el valor del usuario que esta ingresado, importo libreria user
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_creacion = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.titulo

blogUser/models.py
from django.db import models
from django.contrib.auth.models import User
from requests import delete

class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="avatars", null=True, blank=True)

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from blog.models import BlogModel
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.forms import UserCreationForm

from django.http import HttpResponseRedirect
from django.urls import reverse

class BlogList(ListView):

    model = BlogModel
    template_name = "blog/blog_list.html"


class BlogDetail(DetailView):

    model = BlogModel
    template_name = "blog/blog_detail.html"


class BlogCreate(LoginRequiredMixin, CreateView):

    model = BlogModel
    success_url = reverse_lazy("blog_list")
    fields = ["titulo", "sub_titulo", "cuerpo",]
# Cargo el valor autor en funcion del usuario que esta registrdo
    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)


class BlogUpdate(LoginRequiredMixin, UpdateView):

    model = BlogModel
    success_url = reverse_lazy("blog_list")
    fields = ["titulo", "sub_titulo", "cuerpo",]


class BlogDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):

    model = BlogModel
    success_url = reverse_lazy("blog_list")
# verificacion de usuario sea el mismo que lo creo, importo UserPassesTestMixin
    def test_func(self):
     exist = BlogModel.objects.filter(autor=self.request.user.id, id=self.kwargs['pk'])
     return True if exist else False
# Si el usuario no esta autorizado lo derivo a que no es posible
    def handle_no_permission(self):
        return HttpResponseRedirect(reverse("no_autorizado"))

class BlogLogin(LoginView):
    template_name = 'blog/blog_login.html'
    next_page = reverse_lazy("blog_list")


class BlogLogout(LogoutView):
    template_name = 'blog/blog_logout.html'

def no_autorizado(request):
    return render(request, 'blog/bog_no_autorizado.html', )
  

blogUser/views.py
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView, DetailView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User


class SignUp(SuccessMessageMixin, CreateView):
  template_name = 'blogUser/blogUser_crear_acc.html'
  success_url = reverse_lazy('blog_login')
  form_class = UserCreationForm
  success_message = "Perfil Satisfactorio"

class BlogUserProfile(DetailView):

    model = User
    template_name = "blogUser/blogUser_detail.html"


class BlogUserUpdate(LoginRequiredMixin, UpdateView):

    model = User
    template_name = "blogUser/user_form.html"
    fields = ["username", "email", "first_name", "last_name"]

    def get_success_url(self):
      return reverse_lazy("blogUser_profile", kwargs={"pk": self.request.user.id})

blog/templates/blog/blog_detail.html
{% extends "blog/header_footer.html" %}

{% load bootstrap5 %}

{% block cuerpo %}
    <a href="{% url 'blog_list' %}" <button type="button" class="btn btn-secondary"></button>Volver a Lista</a>
    <div>
        <h1>{{object.titulo}}</h1>
        <h2>{{object.sub_titulo}}</h2>
        <p> {{object.cuerpo}} </p>
        <h3>{{object.fecha}}</h3>
        <h3>{{object.autor}}</h3>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "blog/header_footer.html" %}

{% load bootstrap5 %}

{% block cuerpo %}
  {% if user.is_authenticated %}
    <a href="{% url 'blog_logout' %}" <button type="button" class="btn btn-secondary"></button>Salir</a>
    <a href="{% url 'blog_create' %}" <button type="button" class="btn btn-secondary"></button>Nuevo Blog</a>
    <a href="{% url 'blogUser_profile' user.id %}" <button type="button" class="btn btn-secondary"></button>Perfil {{user.username}}</a>
  {% else %}
    <a href="{% url 'blog_login' %}" <button type="button" class="btn btn-secondary"></button>Entrar</a>
    <a href="{% url 'blogUser_signup' %}" <button type="button" class="btn btn-secondary"></button>Crear Cuenta</a>
  {% endif %}
  

  {% if object_list %}
      {% for blog in object_list %}
      <li>
        
          <a href="{% url 'blog_detail' blog.id %}" <button type="button" class="btn btn-secondary"></button>{{blog.titulo}}</a>
          {% if user.is_authenticated %}
            <a href="{% url 'blog_delete' blog.id %}" <button type="button" class="btn btn-secondary"></button>Borrar</a>
            <a href="{% url 'blog_update' blog.id %}" <button type="button" class="btn btn-secondary"></button>Actualizar</a>
          {% endif %}
      </li>
      {% endfor %}
  {% else %}
    <h1> No hay blogs</h1>
  {% endif %}
{% endblock %}

blog/templates/blog/blog_login.html
{% extends "blog/header_footer.html" %}

{% load bootstrap5 %}

{% block cuerpo %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
    <button type="submit" >Iniciar Sesión</button>
    </form>
{% endblock %}

blog/templates/blog/blog_logout.html
{% extends "blog/header_footer.html" %}

{% load bootstrap5 %}

{% block cuerpo %}
    <h1>Saliste de la App</h1>
    <a href="{% url 'blog_list' %}" <button type="button" class="btn btn-secondary"></button>Ir la lista de blogs</a>
{% endblock %}

blog/templates/blog/blogmodel_confirm_delete.html
{% extends "blog/header_footer.html" %}

{% load bootstrap5 %}

{% block cuerpo %}
    <form method="post">{% csrf_token %}
        <p>¿Está Seguro que quiere borrar "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirmar">
    </form>
{% endblock %}

blog/templates/blog/blogmodel_form.html
{% extends "blog/header_footer.html" %}

{% load bootstrap5 %}


{% block cuerpo %}

    <a href="{% url 'blog_list' %}" <button type="button" class="btn btn-secondary"></button>Volver a Lista</a>

    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar">
    </form>
{% endblock %}

blog/templates/blog/bog_no_autorizado.html
{% extends "blog/header_footer.html" %}

{% load bootstrap5 %}

{% block cuerpo %}
  {% if user.is_authenticated %}
    <a href="{% url 'blog_logout' %}" <button type="button" class="btn btn-secondary"></button>Salir</a>
    <a href="{% url 'blog_create' %}" <button type="button" class="btn btn-secondary"></button>Nuevo Blog</a>
    <a href="{% url 'blog_list' %}" <button type="button" class="btn btn-secondary"></button>Volver a Lista</a>
    <a href="{% url 'blogUser_profile' user.id %}" <button type="button" class="btn btn-secondary"></button>Perfil {{user.username}}</a>

  {% else %}
    <a href="{% url 'blog_login' %}" <button type="button" class="btn btn-secondary"></button>Entrar</a>
    <a href="{% url 'blogUser_signup' %}" <button type="button" class="btn btn-secondary"></button>Crear Cuenta</a>
  {% endif %}
  
<h2>"No Autorizado, contactese con el administrador del sitio. Mucha gracias</h2>
  
{% endblock %}

blog/templates/blog/editarPerfil.html
{% extends "blog/header_footer.html" %}

{% load bootstrap5 %}

{% block cuerpo %}

<h1>Editar Perfil</h1>
<h1>De {{usuario}}</h1>


<form action="" method="POST">{% csrf_token %}

    <table>

        {{ miFormulario.as_table }}



    </table>


    <input type="submit", value="Enviar">



</form>
{% endblock %}

blog/templates/blog/header_footer.html
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<!-- <esto es la cabecera/header> -->
<ul class="nav bg-dark fixed">
  <li class="nav-item">
    <a class="nav-link active" href="{%url  'blog_list' %}" style="color:aliceblue"> Blog Coder House </a>
  </li>
</ul>

{% block  cuerpo %}
{% endblock %}

<!-- <esto es el pie/ footer > -->
<ul class="nav bg-dark fixed-bottom justify-content-center">
  <li class="nav-item">
    <a class="nav-link active" href="{%url  'blog_list' %}" style="color:aliceblue">coder house - python 36585 - grupo de Anyel. {% now 'd-m-Y' %}</a>
  </li>
</ul>

blogUser/templates/blogUser/blogUser_crear_acc.html
{% extends "blog/header_footer.html" %}

{% load bootstrap5 %}

{% block cuerpo %}

<a href="{% url 'blog_list' %}" <button type="button" class="btn btn-secondary"></button>Volver a Lista</a>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Crear Cuenta">
</form>

{% endblock %}

blogUser/templates/blogUser/blogUser_detail.html
{% extends "blog/header_footer.html" %}

{% load bootstrap5 %}

{% block cuerpo %}


<a href="{% url 'blog_list' %}" <button type="button" class="btn btn-secondary"></button>Volver a Lista Blogs</a>
<a href="{% url 'blogUser_edit' user.id %}" <button type="button" class="btn btn-secondary"></button>Editar Perfil</a>

<ul>
    <li>Nombre: {{object.first_name}}<li>
    <li>Apellido: {{object.last_name}}<li>
    <li>Correo electronico: {{object.email}} </li>
    <li>Nombre de Usuario: {{object.username}}</li>
</ul>

<img height="138" src="{{ object.avatar_set.first.image.url }}" />

{% endblock %}

blogUser/templates/blogUser/user_form.html
{% extends "blog/header_footer.html" %}

{% load bootstrap5 %}

{% block cuerpo %}

<a href="{% url 'blogUser_profile' user.id %}" <button type="button" class="btn btn-secondary"></button>Volver a Profile</a>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar">
</form>
{% endblock %}